export default {
  title: 'Feedback widget',
  labels: {
    en: {
      step1Title: 'Was this page helpful?',
      step2Title: 'How can we do better?',
      step3Title: 'Thank you for your feedback',
      cancelButtonText: 'Cancel',
      submitButtonText: 'Submit',
      doneButtonText: 'Done',
    },
  },
  themes: {
    ripplex: {
      position: 'right',
      styles: {
        playground: {
          backgroundColor: '#23292F',
          left: 0,
          bottom: 0,
          height: 300,
          position: 'fixed',
        },
        colors: {
          primary: 'blue',
          secondary: 'red',
        },
        font: {
          family: 'Roboto',
          baseWeight: '12px',
          baseColor: 'primary',
        },
        container: {
          fontFamily: 'Roboto',
          color: '#000000',
          backgroundColor: '#FFFFFF',
          borderColor: '',
          borderRadius: 2,
          padding: 0,
          margin: 0,
          width: 360,
          right: 36,
          bottom: 36,
        },
        yesIcon: {
          backgroundImage: 'url(/assets/thumb.svg)',
        },
        noIcon: {
          backgroundImage: 'url(/assets/thumb.svg)',
        },
        step1header: {
          color: '#000000',
          fontWeight: 'bold',
          fontSize: 15,
          background: '#F5F7F9',
          paddingRight: 20,
        },
        step2header: {
          color: '#000000',
          fontWeight: 'bold',
          fontSize: 15,
          background: '#F5F7F9',
        },
        step3: {
          background: 'radial-gradient(156.83% 78.7% at 61.88% 86.04%, rgba(23, 28, 33, 0) 0%, #031B36 100%), radial-gradient(44.33% 47.76% at 5.74% 42.2%, rgba(20, 153, 249, 0.8) 32.68%, rgba(15, 114, 229, 0) 100%), radial-gradient(77.84% 153.29% at 83.57% 149.34%, #1499F9 0%, rgba(16, 131, 231, 0.9) 41.91%, rgba(15, 114, 229, 0) 93.71%), #063975',
          lineHeight: 30,
          paddingLeft: 10,
          height: 150,
        },
        inputForm: {
          height: 100,
          width: '90%',
          margin: 10,
          border: '1px solid #171C21',
        },
        // input[type="submit"]: {
        //   padding: 10,
        //   margin: 10,
        //   alignItems: center,
        //   color: rgb(255, 255, 255),
        //   fontSize: 15,
        //   backgroundColor: rgb(15, 114, 229),
        //   // border: 1px solid rgb(15, 114, 229),
        //   borderRadius: 4,
        // },
        formCancelButton: {
          color: '#999DA2',
          border: 'none',
          fontSize: 15,
          backgroundColor: 'transparent',
          '&:hover': { // doesnt work for basic react
            color: '#494949',
            background: '#ffffff',
          },
        },
        formSubmitButton: {
          color: '#ffffff',
          fontSize: 15,
          backgroundColor: '#0F72E5',
          border: '1px solid #0F72E5',
          borderRadius: 4,
        },
        thankyouDoneButton: {
          color: '#ffffff',
          fontSize: 15,
          backgroundColor: '#0F72E5',
          border: '1px solid #0F72E5',
          borderRadius: 4,
        },
      },
    },
    xrpl: {
      position: 'right',
      styles: {
        playground: {
          backgroundColor: 'black',
          left: 0,
          bottom: 0,
          height: 300,
          position: 'fixed',
        },
        colors: {
          primary: 'Gold',
          secondary: 'Black',
        },
        font: {
          family: 'Work Sans',
          baseWeight: '12px',
          baseColor: 'primary',
        },
        container: {
          fontFamily: 'Work Sans',
          color: 'white',
          backgroundColor: '#000000',
          border: '2px solid #FFFFFF',
          borderColor: '#FFFFFF',
          borderRadius: 0,
          padding: 0,
          margin: 0,
          width: 360,
          right: 36,
          bottom: 100,
        },
        yesIcon: {
          backgroundImage: 'url(/assets/img/fb-thumb.svg)',
        },
        noIcon: {
          backgroundImage: 'url(/assets/img/fb-thumb.svg)',
        },
        step1header: {
          color: '#ffffff',
          fontWeight: 'bold',
          fontSize: 15,
          background: '#000000',
          paddingRight: 20,
        },
        step2header: {
          backgroundImage: 'url(/assets/img/fb-step2header.png)',
          backgroundRepeat: 'no-repeat',
          color: '#ffffff',
          fontWeight: 'bold',
          fontSize: 15,
        },
        step2formarea: {
          background: '#ffffff',
        },
        step2footer: {
          background: '#ffffff',
          paddingRight: 15,
        },
        step3: {
          backgroundImage: 'url(/assets/img/fb-background.png)',
          backgroundRepeat: 'no-repeat',
          lineHeight: 30,
          paddingLeft: 60,
          paddingRight: 60,
          height: 150,
        },
        inputForm: {
          height: 100,
          width: '90%',
          margin: 10,
          border: '1px solid #171C21',
          opacity: 0.5,
        },
        formCancelButton: {
          color: '#999DA2',
          border: 'none',
          fontSize: 15,
          backgroundColor: 'transparent',
          '&:hover': { // doesnt work for basic react
            color: '#494949',
            background: '#ffffff',
          },
        },
        formSubmitButton: {
          color: '#171C21',
          fontSize: 15,
          fontWeight: 'bold',
          backgroundColor: '#ffffff',
          border: '2px solid #171C21',
          borderRadius: 0,
          padding: '8px 16px !important',
        },
        thankyouDoneButton: {
          color: '#fff',
          fontSize: 15,
          fontWeight: 'bold',
          backgroundColor: '#000000',
          border: '2px solid #fff',
          borderRadius: 0,
        },
      },
    },
    paystring: {
      position: 'left',
      styles: {
        playground: {
          backgroundColor: '#000e33',
          left: 0,
          bottom: 0,
          height: 300,
          position: 'fixed',
        },
        colors: {
          primary: 'green',
          secondary: 'blue',
        },
        font: {
          family: 'test',
          baseWeight: '12px',
          baseColor: 'primary',
        },
        container: {
          fontFamily: 'Roboto',
          color: '#000000',
          backgroundColor: '#FFFFFF',
          borderWidth: 1,
          borderStyle: 'solid',
          borderColor: '#e1e4e8',
          borderRadius: 12,
          padding: 0,
          margin: 0,
          width: 360,
          left: 36,
          // right: 164,
          bottom: 36,
        },
        yesIcon: {
          backgroundImage: 'url(https://docforcedevorg.github.io/ripple-feedback-widget/review-apps/Merge210in/2ec120/assets/thumb.svg)',
        },
        noIcon: {
          backgroundImage: 'url(https://docforcedevorg.github.io/ripple-feedback-widget/review-apps/Merge210in/2ec120/assets/thumb.svg)',
        },
        step1header: {
          color: '#000000',
          fontWeight: 'bold',
          fontSize: 15,
          background: '#F5F7F9',
          paddingRight: 20,
        },
        step2header: {
          color: '#000000',
          fontWeight: 'bold',
          fontSize: 15,
          background: '#F5F7F9',
          borderRadius: '10px 10px 0 0',
        },
        step3: {
          backgroundImage: 'url(/assets/feedback_background.png)',
          lineHeight: 30,
          paddingLeft: 10,
          height: 150,
          borderRadius: 12,
        },
        inputForm: {
          height: 100,
          width: '90%',
          margin: 10,
        },
        formCancelButton: {
          color: '#999DA2',
          border: 'none',
          fontSize: 15,
          backgroundColor: 'transparent',
          '&:hover': { // doesnt work for basic react
            color: '#494949',
            background: '#ffffff',
          },
        },
        formSubmitButton: {
          color: '#ffffff',
          fontSize: 15,
          backgroundColor: '#FF8100',
          border: '1px solid #FF8100',
          borderRadius: 4,
        },
        thankyouDoneButton: {
          color: '#ffffff',
          fontSize: 15,
          backgroundColor: '#FF8100',
          border: '1px solid #FF8100',
          borderRadius: 4,
        },
      },
    },
  },
};
